#!/usr/bin/env python3
"""Random 3D scenario generator for the PX4 evaluation.

Builds the maze described in the evaluation plan: n obstacles placed at random,
each a parallelepiped standing on the ground and reaching a randomly chosen
height. Then places k drones at random, each with its own target in 3D space.

Everything is written to one file, scenario.yaml, which is the single source of
truth for the run:

  spawn_obstacles.py   spawns the boxes into the running Gazebo world
  collision_monitor_3d.py  checks the drones against the same boxes
  run_mission.py       flies each drone to its target

Obstacles are spawned into PX4's default world at runtime rather than baked
into a world file, so the PX4 installation stays untouched.

Usage:
  ./gen_scenario_3d.py --n-obstacles 8 --seed 1
  ./gen_scenario_3d.py --n-obstacles 12 --k-drones 3 --seed 4
"""

import argparse
import math
import random
import sys
from pathlib import Path

# Workspace and placement rules.
BOUNDS = 12.0             # scenario elements within [-BOUNDS, BOUNDS]^2
FOOTPRINT = (1.0, 3.0)    # obstacle footprint side range (m)
HEIGHT = (3.0, 10.0)      # obstacle height range (m), always from the ground
OBSTACLE_GAP = 0.5        # minimum gap between obstacle footprints
CLEAR_RADIUS = 2.5        # obstacle-free radius around every start and target
DRONE_GAP = 3.0           # minimum distance between drone start points
MIN_TRAVEL = 12.0         # minimum start-to-target distance per drone
TARGET_Z = (2.0, 8.0)     # target altitude range (m)
START_Z = 0.0             # drones start on the ground and take off
MAX_TRIES = 4000


def rect_circle_clear(rect, cx, cy, radius):
    """True if the circle does not touch the rectangle footprint."""
    x0, x1, y0, y1 = rect
    nx = min(max(cx, x0), x1)
    ny = min(max(cy, y0), y1)
    return math.hypot(cx - nx, cy - ny) > radius


def rects_disjoint(a, b, gap):
    return (a[1] + gap < b[0] or b[1] + gap < a[0] or
            a[3] + gap < b[2] or b[3] + gap < a[2])


def generate_drones(k, rng):
    """Random start points on the ground, each with a 3D target."""
    drones = []
    for _ in range(k):
        for _ in range(MAX_TRIES):
            sx = rng.uniform(-BOUNDS, BOUNDS)
            sy = rng.uniform(-BOUNDS, BOUNDS)
            if all(math.hypot(sx - d["start"][0], sy - d["start"][1]) >= DRONE_GAP
                   for d in drones):
                break
        else:
            sys.exit(f"could not place drone {len(drones) + 1}; lower --k-drones")

        for _ in range(MAX_TRIES):
            tx = rng.uniform(-BOUNDS, BOUNDS)
            ty = rng.uniform(-BOUNDS, BOUNDS)
            tz = rng.uniform(*TARGET_Z)
            if math.hypot(tx - sx, ty - sy) >= MIN_TRAVEL:
                break
        else:
            sys.exit("could not place a target far enough from its start")

        drones.append({"start": (sx, sy, START_Z), "target": (tx, ty, tz)})
    return drones


def generate_obstacles(n, drones, rng):
    """Ground-standing boxes, clear of every start and target, not overlapping."""
    obstacles = []
    keepouts = []
    for d in drones:
        keepouts.append((d["start"][0], d["start"][1]))
        keepouts.append((d["target"][0], d["target"][1]))

    for _ in range(n):
        for _ in range(MAX_TRIES):
            w = rng.uniform(*FOOTPRINT)
            d = rng.uniform(*FOOTPRINT)
            cx = rng.uniform(-BOUNDS + w / 2, BOUNDS - w / 2)
            cy = rng.uniform(-BOUNDS + d / 2, BOUNDS - d / 2)
            rect = (cx - w / 2, cx + w / 2, cy - d / 2, cy + d / 2)

            if not all(rect_circle_clear(rect, kx, ky, CLEAR_RADIUS)
                       for kx, ky in keepouts):
                continue
            if not all(rects_disjoint(rect, o["rect"], OBSTACLE_GAP)
                       for o in obstacles):
                continue

            obstacles.append({"rect": rect, "height": rng.uniform(*HEIGHT)})
            break
        else:
            sys.exit(f"could not place obstacle {len(obstacles) + 1}; "
                     f"lower --n-obstacles or raise BOUNDS")
    return obstacles


def scenario_yaml(seed, n, k, drones, obstacles):
    lines = [
        "# GENERATED by gen_scenario_3d.py - single source of truth for this run.",
        f"seed: {seed}",
        f"n_obstacles: {n}",
        f"k_drones: {k}",
        f"bounds: {BOUNDS}",
        "",
        "drones:",
    ]
    for i, d in enumerate(drones):
        sx, sy, sz = d["start"]
        tx, ty, tz = d["target"]
        euclid = math.dist(d["start"], d["target"])
        lines.append(f"  - id: {i}")
        lines.append(f"    start: {{x: {sx:.3f}, y: {sy:.3f}, z: {sz:.3f}}}")
        lines.append(f"    target: {{x: {tx:.3f}, y: {ty:.3f}, z: {tz:.3f}}}")
        lines.append(f"    euclidean_distance: {euclid:.3f}")
    lines.append("")
    lines.append("# Boxes standing on the ground: z spans 0 to height.")
    lines.append("obstacles:")
    for ob in obstacles:
        x0, x1, y0, y1 = ob["rect"]
        lines.append(f"  - {{x_min: {x0:.3f}, x_max: {x1:.3f}, "
                     f"y_min: {y0:.3f}, y_max: {y1:.3f}, "
                     f"z_min: 0.000, z_max: {ob['height']:.3f}}}")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--n-obstacles", type=int, required=True)
    ap.add_argument("--seed", type=int, required=True)
    ap.add_argument("--k-drones", type=int, default=1)
    ap.add_argument("--out", type=Path, default=None,
                    help="output directory "
                         "(default: scenarios3d/s<seed>_n<N>_k<K>)")
    args = ap.parse_args()

    out = args.out or (Path(__file__).parent / "scenarios3d"
                       / f"s{args.seed}_n{args.n_obstacles}_k{args.k_drones}")
    out.mkdir(parents=True, exist_ok=True)

    rng = random.Random(args.seed)
    drones = generate_drones(args.k_drones, rng)
    obstacles = generate_obstacles(args.n_obstacles, drones, rng)

    (out / "scenario.yaml").write_text(
        scenario_yaml(args.seed, args.n_obstacles, args.k_drones,
                      drones, obstacles))

    print(f"scenario written to {out}/")
    print(f"  {len(obstacles)} obstacle(s), {len(drones)} drone(s)")
    for i, d in enumerate(drones):
        sx, sy, sz = d["start"]
        tx, ty, tz = d["target"]
        print(f"  drone {i}: start=({sx:.1f},{sy:.1f},{sz:.1f}) "
              f"target=({tx:.1f},{ty:.1f},{tz:.1f}) "
              f"euclid={math.dist(d['start'], d['target']):.1f} m")
    print()
    print(f"run it:   ./start_px4_sitl.sh --scenario {out}")
    print(f"          ./spawn_obstacles.py --scenario {out}")


if __name__ == "__main__":
    main()
